services:
  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: otus_postgres
    volumes:
      - ./.Docker/postgres/initdb/:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: otus_app
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    container_name: otus_pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin


volumes:
  pgadmin: