apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    isDefault: false

  - name: PostgreSQL-master
    type: postgres
    access: proxy
    url: db:5432
    database: postgres
    user: postgres
    password: postgres
    isDefault: false
    jsonData:
      sslmode: "disable"
      postgresVersion: 1700

  - name: PostgreSQL-slave-1
    type: postgres
    access: proxy
    url: postgres_slave_1:5432
    database: postgres
    user: postgres
    password: postgres
    isDefault: false
    jsonData:
      sslmode: "disable"
      postgresVersion: 1700

  - name: PostgreSQL-slave-2
    type: postgres
    access: proxy
    url: postgres_slave_2:5432
    database: postgres
    user: postgres
    password: postgres
    isDefault: false
    jsonData:
      sslmode: "disable"
      postgresVersion: 1700

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"